### ISSUE TITLE
Attention weights not found in Pretrained models?

### ISSUE THREAD

**Issue by Tony363** [zizheng-guo/RhythmMamba#2]
Hi,

The server that I am working with does not have enough storage to preprocess all my videos before I extract the rPPG signals using RhythmMamba. I am currently doing the preprocessing in runtime. I was checking what exactly happens in the data loader to confirm that I am writing the my dataloader correctly. However when making sure that my original dataloader for my custom dataset actually works, I failed to load the pretrained weights. Where might I find the weights for the below layers that says the Pretrained weights are missing?

`Traceback (most recent call last):
  File "/home/tony/RhythmMamba/main.py", line 303, in <module>
    test(config, data_loader_dict)
  File "/home/tony/RhythmMamba/main.py", line 92, in test
    model_trainer.test(data_loader_dict)
  File "/home/tony/RhythmMamba/neural_methods/trainer/RhythmMambaTrainer.py", line 130, in test
    return self.student_test(data_loader)
  File "/home/tony/RhythmMamba/neural_methods/trainer/RhythmMambaTrainer.py", line 192, in student_test
    self.model.load_state_dict(ckpt)
  File "/home/tony/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 2152, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for DataParallel:
        Missing key(s) in state_dict: "module.blocks.0.attn.mamba.A_b_log", "module.blocks.0.attn.mamba.D_b", "module.blocks.0.attn.mamba.conv1d_b.weight", "module.blocks.0.attn.mamba.conv1d_b.bias", "module.blocks.0.attn.mamba.x_proj_b.weight", "module.blocks.0.attn.mamba.dt_proj_b.weight", "module.blocks.0.attn.mamba.dt_proj_b.bias", "module.blocks.1.attn.mamba.A_b_log", "module.blocks.1.attn.mamba.D_b", "module.blocks.1.attn.mamba.conv1d_b.weight", "module.blocks.1.attn.mamba.conv1d_b.bias", "module.blocks.1.attn.mamba.x_proj_b.weight", "module.blocks.1.attn.mamba.dt_proj_b.weight", "module.blocks.1.attn.mamba.dt_proj_b.bias", "module.blocks.2.attn.mamba.A_b_log", "module.blocks.2.attn.mamba.D_b", "module.blocks.2.attn.mamba.conv1d_b.weight", "module.blocks.2.attn.mamba.conv1d_b.bias", "module.blocks.2.attn.mamba.x_proj_b.weight", "module.blocks.2.attn.mamba.dt_proj_b.weight", "module.blocks.2.attn.mamba.dt_proj_b.bias", "module.blocks.3.attn.mamba.A_b_log", "module.blocks.3.attn.mamba.D_b", "module.blocks.3.attn.mamba.conv1d_b.weight", "module.blocks.3.attn.mamba.conv1d_b.bias", "module.blocks.3.attn.mamba.x_proj_b.weight", "module.blocks.3.attn.mamba.dt_proj_b.weight", "module.blocks.3.attn.mamba.dt_proj_b.bias", "module.blocks.4.attn.mamba.A_b_log", "module.blocks.4.attn.mamba.D_b", "module.blocks.4.attn.mamba.conv1d_b.weight", "module.blocks.4.attn.mamba.conv1d_b.bias", "module.blocks.4.attn.mamba.x_proj_b.weight", "module.blocks.4.attn.mamba.dt_proj_b.weight", "module.blocks.4.attn.mamba.dt_proj_b.bias", "module.blocks.5.attn.mamba.A_b_log", "module.blocks.5.attn.mamba.D_b", "module.blocks.5.attn.mamba.conv1d_b.weight", "module.blocks.5.attn.mamba.conv1d_b.bias", "module.blocks.5.attn.mamba.x_proj_b.weight", "module.blocks.5.attn.mamba.dt_proj_b.weight", "module.blocks.5.attn.mamba.dt_proj_b.bias", "module.blocks.6.attn.mamba.A_b_log", "module.blocks.6.attn.mamba.D_b", "module.blocks.6.attn.mamba.conv1d_b.weight", "module.blocks.6.attn.mamba.conv1d_b.bias", "module.blocks.6.attn.mamba.x_proj_b.weight", "module.blocks.6.attn.mamba.dt_proj_b.weight", "module.blocks.6.attn.mamba.dt_proj_b.bias", "module.blocks.7.attn.mamba.A_b_log", "module.blocks.7.attn.mamba.D_b", "module.blocks.7.attn.mamba.conv1d_b.weight", "module.blocks.7.attn.mamba.conv1d_b.bias", "module.blocks.7.attn.mamba.x_proj_b.weight", "module.blocks.7.attn.mamba.dt_proj_b.weight", "module.blocks.7.attn.mamba.dt_proj_b.bias", "module.blocks.8.attn.mamba.A_b_log", "module.blocks.8.attn.mamba.D_b", "module.blocks.8.attn.mamba.conv1d_b.weight", "module.blocks.8.attn.mamba.conv1d_b.bias", "module.blocks.8.attn.mamba.x_proj_b.weight", "module.blocks.8.attn.mamba.dt_proj_b.weight", "module.blocks.8.attn.mamba.dt_proj_b.bias", "module.blocks.9.attn.mamba.A_b_log", "module.blocks.9.attn.mamba.D_b", "module.blocks.9.attn.mamba.conv1d_b.weight", "module.blocks.9.attn.mamba.conv1d_b.bias", "module.blocks.9.attn.mamba.x_proj_b.weight", "module.blocks.9.attn.mamba.dt_proj_b.weight", "module.blocks.9.attn.mamba.dt_proj_b.bias", "module.blocks.10.attn.mamba.A_b_log", "module.blocks.10.attn.mamba.D_b", "module.blocks.10.attn.mamba.conv1d_b.weight", "module.blocks.10.attn.mamba.conv1d_b.bias", "module.blocks.10.attn.mamba.x_proj_b.weight", "module.blocks.10.attn.mamba.dt_proj_b.weight", "module.blocks.10.attn.mamba.dt_proj_b.bias", "module.blocks.11.attn.mamba.A_b_log", "module.blocks.11.attn.mamba.D_b", "module.blocks.11.attn.mamba.conv1d_b.weight", "module.blocks.11.attn.mamba.conv1d_b.bias", "module.blocks.11.attn.mamba.x_proj_b.weight", "module.blocks.11.attn.mamba.dt_proj_b.weight", "module.blocks.11.attn.mamba.dt_proj_b.bias", "module.blocks.12.attn.mamba.A_b_log", "module.blocks.12.attn.mamba.D_b", "module.blocks.12.attn.mamba.conv1d_b.weight", "module.blocks.12.attn.mamba.conv1d_b.bias", "module.blocks.12.attn.mamba.x_proj_b.weight", "module.blocks.12.attn.mamba.dt_proj_b.weight", "module.blocks.12.attn.mamba.dt_proj_b.bias", "module.blocks.13.attn.mamba.A_b_log", "module.blocks.13.attn.mamba.D_b", "module.blocks.13.attn.mamba.conv1d_b.weight", "module.blocks.13.attn.mamba.conv1d_b.bias", "module.blocks.13.attn.mamba.x_proj_b.weight", "module.blocks.13.attn.mamba.dt_proj_b.weight", "module.blocks.13.attn.mamba.dt_proj_b.bias", "module.blocks.14.attn.mamba.A_b_log", "module.blocks.14.attn.mamba.D_b", "module.blocks.14.attn.mamba.conv1d_b.weight", "module.blocks.14.attn.mamba.conv1d_b.bias", "module.blocks.14.attn.mamba.x_proj_b.weight", "module.blocks.14.attn.mamba.dt_proj_b.weight", "module.blocks.14.attn.mamba.dt_proj_b.bias", "module.blocks.15.attn.mamba.A_b_log", "module.blocks.15.attn.mamba.D_b", "module.blocks.15.attn.mamba.conv1d_b.weight", "module.blocks.15.attn.mamba.conv1d_b.bias", "module.blocks.15.attn.mamba.x_proj_b.weight", "module.blocks.15.attn.mamba.dt_proj_b.weight", "module.blocks.15.attn.mamba.dt_proj_b.bias", "module.blocks.16.attn.mamba.A_b_log", "module.blocks.16.attn.mamba.D_b", "module.blocks.16.attn.mamba.conv1d_b.weight", "module.blocks.16.attn.mamba.conv1d_b.bias", "module.blocks.16.attn.mamba.x_proj_b.weight", "module.blocks.16.attn.mamba.dt_proj_b.weight", "module.blocks.16.attn.mamba.dt_proj_b.bias", "module.blocks.17.attn.mamba.A_b_log", "module.blocks.17.attn.mamba.D_b", "module.blocks.17.attn.mamba.conv1d_b.weight", "module.blocks.17.attn.mamba.conv1d_b.bias", "module.blocks.17.attn.mamba.x_proj_b.weight", "module.blocks.17.attn.mamba.dt_proj_b.weight", "module.blocks.17.attn.mamba.dt_proj_b.bias", "module.blocks.18.attn.mamba.A_b_log", "module.blocks.18.attn.mamba.D_b", "module.blocks.18.attn.mamba.conv1d_b.weight", "module.blocks.18.attn.mamba.conv1d_b.bias", "module.blocks.18.attn.mamba.x_proj_b.weight", "module.blocks.18.attn.mamba.dt_proj_b.weight", "module.blocks.18.attn.mamba.dt_proj_b.bias", "module.blocks.19.attn.mamba.A_b_log", "module.blocks.19.attn.mamba.D_b", "module.blocks.19.attn.mamba.conv1d_b.weight", "module.blocks.19.attn.mamba.conv1d_b.bias", "module.blocks.19.attn.mamba.x_proj_b.weight", "module.blocks.19.attn.mamba.dt_proj_b.weight", "module.blocks.19.attn.mamba.dt_proj_b.bias", "module.blocks.20.attn.mamba.A_b_log", "module.blocks.20.attn.mamba.D_b", "module.blocks.20.attn.mamba.conv1d_b.weight", "module.blocks.20.attn.mamba.conv1d_b.bias", "module.blocks.20.attn.mamba.x_proj_b.weight", "module.blocks.20.attn.mamba.dt_proj_b.weight", "module.blocks.20.attn.mamba.dt_proj_b.bias", "module.blocks.21.attn.mamba.A_b_log", "module.blocks.21.attn.mamba.D_b", "module.blocks.21.attn.mamba.conv1d_b.weight", "module.blocks.21.attn.mamba.conv1d_b.bias", "module.blocks.21.attn.mamba.x_proj_b.weight", "module.blocks.21.attn.mamba.dt_proj_b.weight", "module.blocks.21.attn.mamba.dt_proj_b.bias", "module.blocks.22.attn.mamba.A_b_log", "module.blocks.22.attn.mamba.D_b", "module.blocks.22.attn.mamba.conv1d_b.weight", "module.blocks.22.attn.mamba.conv1d_b.bias", "module.blocks.22.attn.mamba.x_proj_b.weight", "module.blocks.22.attn.mamba.dt_proj_b.weight", "module.blocks.22.attn.mamba.dt_proj_b.bias", "module.blocks.23.attn.mamba.A_b_log", "module.blocks.23.attn.mamba.D_b", "module.blocks.23.attn.mamba.conv1d_b.weight", "module.blocks.23.attn.mamba.conv1d_b.bias", "module.blocks.23.attn.mamba.x_proj_b.weight", "module.blocks.23.attn.mamba.dt_proj_b.weight", "module.blocks.23.attn.mamba.dt_proj_b.bias". `

**Comment by zizheng-guo** [comment]
I tried to clone the code again and ran it immediately without errors. I also tried to update the Mamba version to the latest with no errors. Are you sure you haven't changed the code in the model file? The pre-training checkpoint has little to do with the dataloader.

**Comment by Tony363** [comment]
First of all, I really really appreciate your prompt feedback! I am currently trying to use RythmMamba and RythmFormer to extract rPPG signals. I forked your RythmMamba [here](https://github.com/Tony363/RhythmMamba) and am currently writing my own dataloader. I don't think I edited the code in the model file, maybe I loaded the checkpoint wrong? I think loading the pretrained weights from the `Pretrained/` directory comes after fitting the model in to DataParallel?

Would you kindly check whether there is anything wrong that I might have changed unknowingly?

Again, I greatly appreciate your assistance!

**Comment by zizheng-guo** [comment]
The error message indicates that the model file and checkpoint do not match. But there seems to be nothing wrong with your code.
Your current git code may be inconsistent with your local version, and line 192 is not the error description self.model.load_state_dict(ckpt)
You can print the pre-training checkpoint information, compare them to the model file, and determine what is the problem.

**Comment by Tony363** [comment]
Thank you again for checking out my code and dataloaders. I actually managed to get Rhythmformer working to extract rPPG signals using the same dataloader and configurations for RhythmMamba.  I did not face the issue with the missing fusion stem attention weights using RhythmFormer. Just for a sanity check, could you possibly send me the RhythmMamba weights for me to check? I was checking the layer names between the instantiated model and the loaded checkpoint weights 2 days ago and got a list of layers that are not in the instantiated model of RhythmMamba.

I have attached a log file where I tried to log the missing layers from the checkpoint weights and I have also pushed my latest commit to my forked RhythmMamba repo on the "nopreprocess" branch. Would you also kindly verify the configurations and code if I made any blatant errors?
[logger.log](https://github.com/user-attachments/files/16045939/logger.log)

**Comment by zizheng-guo** [comment]
RhythmMamba weights can be printed from the supplied checkpoint file and your code file seems to be fine as well. It is difficult to tell from the log file whether checkpoint lacks MAMBA-related weights or the model file lacks definitions.  Is it possible that there are some problems with the mamba library that cause these variables to not be defined in mamba, or you can simulate training and compare the output checkpoint with the provided checkpoint

**Comment by Tony363** [comment]
Thank you very much for the reply! I'll try once more to reinstall my dependencies. As for as the code goes, I'll just use the working version from RhythmFormer. I'll update how it goes!

**Comment by Tony363** [comment]
It seems compiling Mamba with or the Causal1d with the most up to date nvidia driver for pytorch would fix this issues.
