### ISSUE TITLE
训练时loss很高

### ISSUE THREAD

**Issue by 408550969** [zizheng-guo/RhythmMamba#5]
使用自己的数据集，训练时loss在4.7左右，虽然最后MAE降到了1.2，比EFFICIENTPHYS要高，这正常吗？

**Comment by zizheng-guo** [comment]
配置没改动的话loss是正常的，数据集内训练如果数据集比较简单的话这些方法的精度应该都差不太多。你也可以可视化训练过程的loss和结果确认是收敛的，相邻epoch之间精度差异挺大的

**Comment by zizheng-guo** [comment]
配置没改动的话loss是正常的，你可以可视化训练过程的loss和结果确认是收敛的，相邻epoch之间精度差异挺大的
